import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, extname } from 'node:path';
import { minimatch } from './minimatch.mjs';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const SOURCE_EXTENSIONS = new Set([
  '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs',
  '.py', '.go', '.rs', '.java', '.kt', '.swift',
  '.vue', '.svelte', '.astro',
]);

const IGNORE_DIRS = new Set([
  'node_modules', '.git', 'dist', 'build', 'out', '.next',
  '.nuxt', 'coverage', '__pycache__', '.resonant-code', '.playbook',
  'vendor', 'target',
]);

// ---------------------------------------------------------------------------
// Internals
// ---------------------------------------------------------------------------

/**
 * Recursively collects candidate source files while skipping build and tool output.
 *
 * @param {string} dir
 * @param {string} projectRoot
 * @returns {string[]}
 */
function walkDir(dir, projectRoot) {
  const results = [];
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return results;
  }
  for (const entry of entries) {
    if (IGNORE_DIRS.has(entry.name)) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...walkDir(full, projectRoot));
    } else if (entry.isFile() && SOURCE_EXTENSIONS.has(extname(entry.name))) {
      results.push(relative(projectRoot, full).replace(/\\/g, '/'));
    }
  }
  return results;
}

/**
 * Loads optional repo context generated by other tooling for prompt enrichment.
 *
 * @param {string} projectRoot
 * @returns {{ raw: string } | null}
 */
function loadContextMeta(projectRoot) {
  try {
    const contextPath = join(projectRoot, '.resonant-code', 'context', 'global.yaml');
    const raw = readFileSync(contextPath, 'utf-8');
    // Keep a summary snippet for prompt enrichment — no full YAML parse needed
    return { raw: raw.slice(0, 800) };
  } catch {
    return null;
  }
}

// ---------------------------------------------------------------------------
// Public
// ---------------------------------------------------------------------------

/**
 * Collect source files within projectRoot matching scopeGlob.
 *
 * @param {string} projectRoot
 * @param {string} scopeGlob — glob pattern relative to projectRoot (default: "src/**")
 * @returns {{ files: string[], contextMeta: object | null }}
 */
export function collectScope(projectRoot, scopeGlob = 'src/**') {
  const contextMeta = loadContextMeta(projectRoot);
  const allFiles = walkDir(projectRoot, projectRoot);
  const files = allFiles.filter(f => minimatch(f, scopeGlob));
  return { files, contextMeta };
}
