export default {
  entry: ['./src/index.ts', './src/**/*.ts'],
  format: 'esm',
  outDir: 'dist',
  platform: 'node',
  target: 'node22',
  unbundle: true,
  root: 'src',
  clean: true,
  dts: false,
  sourcemap: false,
  fixedExtension: true,
  tsconfig: './tsconfig.json',
  hash: false,
};
